"""
Phase 7: Hybrid model. 5-fold out-of-fold (OOF) BiLSTM probabilities
appended to the 12 tabular scores -> XGBoost (13 features), matching the
original methodology's design (chat_history.md SS3) -- this component
was already leakage-free by construction in the original design (OOF
predictions are never generated by a model that saw that fold), so the
procedure is kept as-is.

Reuses the exact same 80/20 train/test split as Phase 4/5 (same
random_state=42, same source dataframe) so all internal-set comparisons
in the final report line up across every model.

NOTE: this is the older BiLSTM-sequence hybrid, not the project's canonical
"Hybrid-B" (XGBoost + MLP base learners -> logistic-regression meta-learner,
external AUC 0.998, see docs/memory/project_hybrid_mldl.md). Hybrid-B's own
generating script does not exist anywhere in the repo -- only its results
table (2/results/table_hybrid_mldl.csv) survived, the same kind of gap as the
missing SMOTE-sweep script noted in CLAUDE.md. Kept running this script
because it's the only hybrid that's actually reproducible right now;
rebuilding Hybrid-B is separate, undecided work.

2026-07-25 (Stage 4): added BayesDel_noAF_score as a 12th tabular score -- see
new_scripts/04_filter_and_report.py's docstring for the decision rationale.
"""
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import roc_auc_score, accuracy_score, precision_score, recall_score, f1_score
from Bio import SeqIO
from xgboost import XGBClassifier

torch.backends.cudnn.enabled = False
device = "cuda" if torch.cuda.is_available() else "cpu"

SCORE_COLS = [
    "ClinPred_score", "MetaRNN_score", "REVEL_score", "MetaSVM_score", "MetaLR_score",
    "VEST4_score", "AlphaMissense_score", "PrimateAI_score", "CADD_raw", "CADD_phred",
    "ESM1b_score", "BayesDel_noAF_score", "Eigen_raw_coding",
]
REGIONS = {13: ("pipeline/dl/chr13_region.fasta", 32314843), 17: ("pipeline/dl/chr17_region.fasta", 43039371)}
WINDOW = 100
BASES = "ACGT"
BASE_IDX = {b: i for i, b in enumerate(BASES)}


class BiLSTMModel(nn.Module):
    def __init__(self, in_channels=4, hidden=64):
        super().__init__()
        self.lstm = nn.LSTM(in_channels, hidden, batch_first=True, bidirectional=True)
        self.fc = nn.Sequential(nn.Linear(hidden * 2, 64), nn.ReLU(), nn.Dropout(0.3), nn.Linear(64, 1))

    def forward(self, x):
        _, (h_n, _) = self.lstm(x)
        pooled = torch.cat([h_n[0], h_n[1]], dim=1)
        return self.fc(pooled).squeeze(-1)


def one_hot(seq):
    arr = np.zeros((len(seq), 4), dtype=np.float32)
    for i, b in enumerate(seq):
        idx = BASE_IDX.get(b)
        if idx is not None:
            arr[i, idx] = 1.0
    return arr


def load_regions():
    seqs = {}
    for chrom, (path, start) in REGIONS.items():
        rec = next(SeqIO.parse(path, "fasta"))
        seqs[chrom] = (str(rec.seq).upper(), start)
    return seqs


def build_windows(df, seqs):
    X = np.zeros((len(df), WINDOW * 2 + 1, 4), dtype=np.float32)
    for i, (_, row) in enumerate(df.iterrows()):
        seq, region_start = seqs[int(row["chr"])]
        offset = int(row["pos"]) - region_start
        lo, hi = offset - WINDOW, offset + WINDOW + 1
        alt_window = seq[lo:offset] + row["alt"] + seq[offset + 1:hi]
        X[i] = one_hot(alt_window)
    return X


def train_bilstm(X_train, y_train, X_val, epochs=40, lr=5e-4, hidden=64, batch_size=64):
    model = BiLSTMModel(hidden=hidden).to(device)
    pw = torch.tensor([(y_train == 0).sum() / max((y_train == 1).sum(), 1)], device=device)
    criterion = nn.BCEWithLogitsLoss(pos_weight=pw)
    opt = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=1e-5)
    from torch.utils.data import DataLoader, TensorDataset
    ds = TensorDataset(torch.tensor(X_train), torch.tensor(y_train, dtype=torch.float32))
    dl = DataLoader(ds, batch_size=batch_size, shuffle=True)
    for _ in range(epochs):
        model.train()
        for xb, yb in dl:
            xb, yb = xb.to(device), yb.to(device)
            opt.zero_grad()
            loss = criterion(model(xb), yb)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            opt.step()
    model.eval()
    with torch.no_grad():
        proba = torch.sigmoid(model(torch.tensor(X_val).to(device))).cpu().numpy()
    return model, proba


def main():
    df = pd.read_csv("pipeline/internal_ml_ready.csv")
    seqs = load_regions()

    # identical split to Phase 4/5: same source frame, same params
    X_scores = df[SCORE_COLS].apply(pd.to_numeric, errors="coerce")
    y = df["label"].astype(int)
    idx_train, idx_test = train_test_split(
        df.index, test_size=0.2, stratify=y, random_state=42
    )
    train_df = df.loc[idx_train].reset_index(drop=True)
    test_df = df.loc[idx_test].reset_index(drop=True)
    y_train = train_df["label"].astype(int).values
    y_test = test_df["label"].astype(int).values

    print(f"Train: {len(train_df)} ({y_train.sum()} pathogenic)  Test: {len(test_df)} ({y_test.sum()} pathogenic)")

    X_win_train = build_windows(train_df, seqs)
    X_win_test = build_windows(test_df, seqs)

    # 5-fold OOF BiLSTM probabilities on the training portion
    print("Generating 5-fold OOF BiLSTM probabilities on the training set...")
    oof_proba = np.zeros(len(train_df))
    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    for fold, (fit_idx, hold_idx) in enumerate(cv.split(X_win_train, y_train)):
        print(f"  fold {fold+1}/5")
        _, fold_proba = train_bilstm(X_win_train[fit_idx], y_train[fit_idx], X_win_train[hold_idx])
        oof_proba[hold_idx] = fold_proba

    print("Training final BiLSTM on full training set for test-set scoring...")
    final_bilstm, test_proba = train_bilstm(X_win_train, y_train, X_win_test)

    X_train_hybrid = train_df[SCORE_COLS].apply(pd.to_numeric, errors="coerce").copy()
    X_train_hybrid["BiLSTM_oof_proba"] = oof_proba
    X_test_hybrid = test_df[SCORE_COLS].apply(pd.to_numeric, errors="coerce").copy()
    X_test_hybrid["BiLSTM_oof_proba"] = test_proba

    pos_weight = (y_train == 0).sum() / (y_train == 1).sum()
    sample_weight = np.where(y_train == 1, pos_weight, 1.0)

    xgb = XGBClassifier(n_estimators=300, max_depth=4, eval_metric="logloss", random_state=42)
    xgb.fit(X_train_hybrid, y_train, sample_weight=sample_weight)

    proba = xgb.predict_proba(X_test_hybrid)[:, 1]
    pred = xgb.predict(X_test_hybrid)
    results = {
        "Hybrid_XGB": {
            "test_roc_auc": round(roc_auc_score(y_test, proba), 4),
            "test_accuracy": round(accuracy_score(y_test, pred), 4),
            "test_precision": round(precision_score(y_test, pred, zero_division=0), 4),
            "test_recall": round(recall_score(y_test, pred, zero_division=0), 4),
            "test_f1": round(f1_score(y_test, pred, zero_division=0), 4),
        }
    }
    print(results)

    prior = pd.read_csv("pipeline/table_internal_comparison.csv", index_col=0)
    combined = pd.concat([prior, pd.DataFrame(results).T[prior.columns]])
    combined.to_csv("pipeline/table_internal_comparison.csv")
    print("\n=== Full internal comparison (base + ensembles + hybrid) ===")
    print(combined)

    import joblib
    joblib.dump(xgb, "pipeline/models/model_hybrid_xgb.pkl")
    torch.save(final_bilstm.state_dict(), "pipeline/models/model_hybrid_bilstm.pt")


if __name__ == "__main__":
    main()
